version: '3.8'
services:
  web:
    build: './api-app'
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  # closer:
  #   build: './auction-closer'

